/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMealDialog: typeof import('./src/components/AddMealDialog.vue')['default']
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    ErrorDialog: typeof import('./src/components/ErrorDialog.vue')['default']
    RateOrderDialog: typeof import('./src/components/RateOrderDialog.vue')['default']
    RestaurantSidebar: typeof import('./src/components/RestaurantSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessDialog: typeof import('./src/components/successDialog.vue')['default']
    WorkerSidebar: typeof import('./src/components/WorkerSidebar.vue')['default']
  }
}
